using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

using Image = UnityEngine.UI.Image;

public class Health : MonoBehaviour
{
    public int playerHealth;
    public int numOfHearts;

    public Image[] hearts;
    public Sprite fullHeart;
    public Sprite emptyHeart;

    // Update is called once per frame
    void Update()
    {
        for (int i = 0; i < hearts.Length; i++)
        {
            if (i < playerHealth)
            {
                hearts[i].sprite = fullHeart;
            }
            else
            {
                hearts[i].sprite = emptyHeart;
            }

            if (i < numOfHearts)
            {
                hearts[i].enabled = true;
            }
            else
            {
                hearts[i].enabled = false;
            }
        }
    }

    public void plantDamaged(){
        playerHealth--;
    }
}
